name: Workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
      - name: Run gradle checkstyle
        run: ./gradlew checkstyleMain
      - name: Run Gradle checkstyleTest
        run: ./gradlew checkstyleTest
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: 2620a205957d1ee21889975c13b449dcf52c133b0b7da8fdfa0a0b196615d8cd
          JACOCO_SOURCE_PATH: src/main/java 
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml --coverage-input-type jacoco
