name: Workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
      - name: Run gradle wrapper
        run: gradle wrapper
      - name: Run gradle checkstyle
        run: ./gradlew checkstyleMain
      - name: Run Gradle checkstyleTest
        run: gradle wrapper ./gradlew checkstyleTest
